<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup> 
    <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.5.8" /> 
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.6" /> 
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InternetMarket.PaymentService.Domain\InternetMarket.PaymentService.Domain.csproj" />
    <ProjectReference Include="..\InternetMarket.PaymentService.Application\InternetMarket.PaymentService.Application.csproj" />
  </ItemGroup>

</Project>
